import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateStudyNote = async (specialtyName: string, topicTitle: string): Promise<string> => {
  // Your provided notes have been added here.
  // The quiz will be generated by Gemini based on the title and specialty.
  const userGeneratedNote = `
# HERO_START
Title: ${topicTitle}
Subtitle: ${specialtyName} | User Generated Note
Definition: Acute appendicitis is acute inflammation of the vermiform appendix, most likely due to obstruction of the lumen of the appendix.
Stats: 
- Peak Incidence: 10-30 years
- M:F Ratio: 1.4:1
- Mortality: <1% for uncomplicated, 5-15% if perforated
- Perforation Rate: 15-20%
- Critical Threshold: N/A
# HERO_END

## Aetiology & Pathophysiology
**AETIOLOGY**
*   Lymphoid hyperplasia (60%) - associated with viral infections (measles, mononucleosis), Crohn's disease
*   Faecolith/appendicolith (35%)
*   Fibrotic strictures of the appendix - from previous episodes of inflammation
*   Foreign bodies - fruit seeds, pins, worms (parasites)
*   Tumours - carcinoid tumours, caecal carcinoma

**PATHOPHYSIOLOGY**
Obstruction of appendiceal lumen → bacterial overgrowth → increased intraluminal pressure → venous congestion → ischaemia → necrosis → perforation

## History
**I. HISTORY**
**Presenting Complaint**
*   Abdominal pain

**History of Presenting Complaint**
Onset and progression of pain:
*   Initial periumbilical/epigastric pain - moderate intensity, colicky or dull ache in nature (visceral pain from T10 dermatome)
*   Migration of pain to the right iliac fossa (parietal peritoneal irritation) - a hallmark feature

Site variations depending on appendix position:
*   Retrocaecal appendix - pain at right flank
*   Pelvic appendix - deep pelvic discomfort, dysuria
*   Subhepatic appendix - right upper quadrant pain

Aggravating and alleviating factors:
*   Aggravating: coughing, sneezing, or sudden movement exacerbates the pain
*   Alleviating: analgesics, lying still

Associated symptoms:
*   Anorexia (almost universal - its absence should prompt reconsideration of the diagnosis)
*   Nausea and vomiting (typically after onset of pain - pain before vomiting suggests surgical cause)
*   Low-grade fever
*   Constipation or diarrhoea
*   Dysuria or frequency (if appendix near bladder)
*   Right lower abdominal swelling (in late presentations)

## Physical Examination
**II. PHYSICAL EXAMINATION**
**General Examination**
*   General appearance - note distress, posture (lying still suggests peritoneal irritation)
*   Dehydration
*   Febrile - usually low-grade fever (<38.5°C)
*   Tachycardia
*   Furred/coated tongue

**Abdominal Examination**
*   **Inspection:** Abdominal distension, Scars, Patient lying still.
*   **Palpation:** Tenderness at McBurney's point, Rebound tenderness and guarding, Muscle spasm, Rovsing's sign, Psoas sign, Obturator sign.
*   **Percussion:** Tenderness at RIF, Loss of liver dullness (perforation).
*   **Auscultation:** Bowel sounds may be reduced or absent.

**Digital Rectal Examination (DRE)**
*   Right-sided tenderness suggests pelvic appendicitis.

## Investigations
**III. INVESTIGATIONS**
**Laboratory Investigations**
*   **FBC:** Leucocytosis with neutrophilia (WBC >10,000/mm³)
*   **CRP & ESR:** Elevated
*   **Urine Analysis:** To rule out UTI
*   **Urine beta-hCG:** Mandatory in all females of childbearing age

**Imaging**
*   **Ultrasound:** Non-compressible appendix >6mm.
*   **CT Scan:** Most accurate; shows dilated appendix, fat stranding.
*   **MRI:** Preferred in pregnancy.

## Scoring Systems
**Alvarado Score (MANTRELS)**
*   **M** - Migration of pain (1)
*   **A** - Anorexia (1)
*   **N** - Nausea/Vomiting (1)
*   **T** - Tenderness in RIF (2)
*   **R** - Rebound tenderness (1)
*   **E** - Elevated temperature (1)
*   **L** - Leucocytosis (2)
*   **S** - Shift to left (1)

*Score 7-10 suggests high probability of appendicitis.*

## Differential Diagnosis
**General:** Gastroenteritis, Mesenteric adenitis, Meckel's diverticulitis, Crohn's, UTI, Perforated peptic ulcer.
**Gynaecological:** Ectopic pregnancy, Ovarian torsion, PID, Mittelschmerz.
**Paediatric:** Intussusception, Lobar pneumonia.

## Management
**IV. TREATMENT**
**Initial Management:** NBM, IV fluids, Analgesia, IV antibiotics (if perforation suspected).

**1. Uncomplicated Appendicitis**
*   **Emergency Appendicectomy** (Open or Laparoscopic). Laparoscopic is preferred.

**2. Appendix Mass (>3-5 days)**
*   **Conservative Management (Ochsner-Sherren Regimen):** NBM, IV fluids, IV antibiotics, analgesia, and close monitoring of the mass size.
*   **Interval Appendicectomy** after 6-8 weeks.

**3. Appendix Abscess**
*   **CT-guided drainage** OR surgical drainage.
*   Followed by interval appendicectomy.

## Complications
**Early**
*   Gangrenous appendix
*   Perforation
*   Peritonitis
*   Appendix mass/abscess
*   Sepsis
*   Portal pyaemia (pylephlebitis)

**Late**
*   Adhesions and intestinal obstruction
*   Infertility (females)
*   Enterocutaneous fistula

## Key Points & Clinical Pearls
*   Classic presentation: Periumbilical pain migrating to RIF with anorexia.
*   Pain before vomiting suggests a surgical abdomen.
*   McBurney's point tenderness is the most reliable sign.
*   CT scan is the most accurate imaging modality; MRI preferred in pregnancy.
*   Do not delay analgesia - it does not mask clinical signs.
*   Higher perforation risk in extremes of age and delayed presentation.
> [PEARL] "When in doubt, take it out!" - The risk of negative appendicectomy is less than the risk of perforation from delayed surgery.
  `;
  
  return Promise.resolve(userGeneratedNote);
};

export interface QuizQuestion {
  question: string;
  options: string[];
  answer: string;
  explanation: string;
}

export const generateQuiz = async (specialtyName: string, topicTitle: string): Promise<QuizQuestion[]> => {
  try {
    const prompt = `
      Generate 5 high-yield multiple-choice questions (MCQs) for medical students regarding "${topicTitle}" in "${specialtyName}".
      Focus on clinical scenarios, diagnosis, and management relevant to the Nigerian context.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              question: { type: Type.STRING },
              options: { 
                type: Type.ARRAY,
                items: { type: Type.STRING }
              },
              answer: { 
                type: Type.STRING,
                description: "The correct option text, must match one of the options exactly."
              },
              explanation: { type: Type.STRING }
            },
            required: ["question", "options", "answer", "explanation"]
          }
        }
      }
    });

    if (response.text) {
      return JSON.parse(response.text) as QuizQuestion[];
    }
    return [];
  } catch (error) {
    console.error("Gemini Quiz Error:", error);
    throw new Error("Failed to generate quiz.");
  }
};
